print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/zmziauddin/IntermediateGame/ProjectEcco/Assets/pokeball.ma"`)
{		
	file -o "/Users/zmziauddin/IntermediateGame/ProjectEcco/Assets/pokeball.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/zmziauddin/IntermediateGame/ProjectEcco/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/zmziauddin/IntermediateGame/ProjectEcco/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/zmziauddin/IntermediateGame/ProjectEcco/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
